name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./C2-AgileDevelopmentwithAzure/automated_build_exercise/starter_files

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
        working-directory: ${{env.working-directory}}
    - name: Install dependencies
      run: |
        make install
      working-directory: ${{env.working-directory}}
    - name: Lint with pylint
      run: |
        make lint
      working-directory: ${{env.working-directory}}
    - name: Test with pytest
      run: |
        make test
      working-directory: ${{env.working-directory}}
